before_install:
- openssl aes-256-cbc -K $encrypted_8b31a5c0241d_key -iv $encrypted_8b31a5c0241d_iv
  -in deploy-key.enc -out deploy-key -d

language: node_js
node_js:
  - "node"
  - "7"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: 188.166.80.175
before_install:
  - bash _scripts/install.sh
script:
  - bash _scripts/build.sh
  - bash _scripts/test.sh
after_success:
  - bash _scripts/deploy.sh