language: node_js
node_js:
  - node
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
addons:
  ssh_known_hosts: 188.166.80.175
branches:
  only:
  - master
before_install:
  - bash .travis/install.sh
script:
  - bash .travis/build.sh
  - bash .travis/test.sh
before_deploy:
  - cd dist
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true
notifications:
  email: false
